[versions]
kotlin = "1.9.22"
spring-boot = "3.2.0"
dependency-management = "1.1.4"
jib = "3.4.0"
sonarqube = "4.4.1.3373"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "dependency-management" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
